Ignore git for certaint directories
jorgebucaran/hydro pull request #30
Opened 2022-03-24 23:41 UTC by lgehr

I added a new configuration variable `$hydro_ignored_git_paths` where you can put
paths you do not want hydro to display git information in the prompt.

My use-case is that I have my $HOME in a git repo to manage my dotfiles etc. 

If you like this feature I would make another commit adding the information  in the README.

2022-03-25 01:19 UTC, jorgebucaran requested changes

2022-03-25 01:19 UTC, jorgebucaran commented on conf.d/hydro.fish
> +    if ! contains $hydro_ignored_git_paths
How about we invert the logic here so that we just exit the process and also to prevent the indentation?

2022-03-30 19:01 UTC, lgehr commented
Changed the commit accordingly. 
Also now it ignores the whole repo and not only the git toplevel directory. 

Updated the README, too

2022-03-30 23:07 UTC, jorgebucaran commented
> Also now it ignores the whole repo and not only the git toplevel directory.

Before it would only ignore the top-level directory, but not subdirectories, correct?

2022-03-31 08:36 UTC, lgehr commented
> > Also now it ignores the whole repo and not only the git toplevel directory.
> 
> Before it would only ignore the top-level directory, but not subdirectories, correct?

correct!

2022-05-30 17:10 UTC, merged

2022-05-30 17:31 UTC, jorgebucaran commented
Sorry for the long delay, @lgehr. Just merged your changes. 💯 

I also tweaked the implementation (just a bit) to check for ignored paths if $PWD or $hydro_ignored_git_paths change.